sudo: false

language: python
python:
  - 2.7

jdk:
  - oraclejdk7

branches:
  only:
    - master
    - develop

env:
  global:
    - BASEX_BASE_URL=http://localhost:8984/rest
  matrix:
    - BASEX_DOWNLOAD_URL=http://files.basex.org/releases/7.9/BaseX79.zip

before_install:
  # download and run BaseX server and REST interface
  - pushd .
  - cd ..
  - wget $BASEX_DOWNLOAD_URL
  - unzip BaseX*.zip
  - cd ./basex/bin
  - ./basexhttp -S
  - popd
  - pip install -r requirements.txt
  - pip install coveralls

install:
  - python setup.py install

script:
  - nosetests -v --with-coverage --cover-package pybasex
  
after_success:
  - coveralls
